spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:assignment
    username: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret-key: JSON_WEB_TOKEN_SECRET_KEY_FOR_ASSIGNMENT
  access-expiration: 86400000 # 24 hours
